WebApplication6/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication6.Models;

namespace WebApplication6.Controllers
{   
    public class BasketController : Controller
    {
        private readonly BookStoreContext _context;
        private readonly ShopBasket _basket;

        public BasketController(ShopBasket basket, BookStoreContext context)
        {
            _context = context;
            _basket = basket;
        }
        [HttpGet]

        [Authorize(Roles = "user")]
        public async Task<IActionResult> GetBasketView()
        {
            var items = await _basket.GetBasketItemsAsync();
            _basket.defferedBooks = items;
            ViewData["TotalSum"] = await _basket.GetTotalSumAsync();
            return View(_basket);
        }

        [Authorize(Roles = "user")]
        public  async Task<EmptyResult> AddBasketItem(int id)
        {
            await _basket.AddBasketItemAsync( _context.Book.FirstOrDefault(b => b.ID == id));

            return new EmptyResult();          
        }

       [Authorize(Roles = "user")]
        public async Task<EmptyResult> RemoveBasketItem(int id)
        {
            await _basket.RemoveBasketItemAsync(id);                    
            return new EmptyResult();                    
        }
    }
}

WebApplication6/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication6.Models;
using WebApplication6.Services;

namespace WebApplication6.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly ShopBasket _basket;
        public OrderController(IOrderService orderService, ShopBasket basket)
        {
            _orderService = orderService;
            _basket = basket;
        }

        [Authorize(Roles = "user")]
        public IActionResult Buy()
        {           
            return View();
        }
        
        [Authorize(Roles = "user")]
        [HttpPost]
        public async Task<ActionResult> Buy(Order order)
        {        
            if(!(await _basket.GetBasketItemsAsync()).Any())
            {
                ModelState.AddModelError("", "DSDSDS");
            }
            if(ModelState.IsValid)
            {
                order.orderDateTime = DateTime.Now;
                order.Byer = User.Identity.Name;
                _orderService.createOrder(order);
                return RedirectToAction(nameof(Complete));
            }       
            return View(order);
        }

        [Authorize(Roles = "user")]
        public async Task<IActionResult> Complete()
        {
            await _basket.RemoveAllBasketItems();
            ViewBag.Message = "Order is created!";
            return View();
        }
    }


}

WebApplication6/Views/Order/Buy.cshtml
@model WebApplication6.Models.Order
@{
    ViewData["Title"] = "Buy";
}

    <div class="container-fluid mt-5 pt-3">
        <h1>Order registration</h1>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Buy" asp-controller="Order" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Date" class="col-2 col-form-label"></label>
                        <div class="col-10">
                            <input class="form-control" type="date" value="2011-08-19" asp-for="Date">
                            <span asp-validation-for="Date" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContactPhone" class="control-label"></label>
                        <input asp-for="ContactPhone" class="form-control" />
                        <span asp-validation-for="ContactPhone" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <div class="form-group">
                            <label asp-for="Adress" class="control-label"></label>
                            <textarea class="form-control" rows="5" asp-for="Adress"></textarea>
                        </div>
                        <span asp-validation-for="Adress" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PaymentType" class="control-label"></label>
                        <select asp-for="PaymentType" asp-items="@new SelectList(Enum.GetValues(typeof(PaymentType)))" class="btn  btn-outline-secondary "></select>
                        <span asp-validation-for="PaymentType" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <a asp-action="GetBasketView" asp-controller="Basket" class="btn btn-outline-info">Back to Basket</a> |
                        <input type="submit" value="Create" class="btn btn-outline-info" />

                    </div>
                </form>
            </div>
        </div>
        </div>

WebApplication6/Views/Order/Complete.cshtml
<div class="container mt-5 pt-5" >
    <h1>@ViewBag.Message</h1>
</div>