WebApplication6/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication6.Models;

namespace WebApplication6.Controllers
{   
    public class BasketController : Controller
    {
        private readonly BookStoreContext _context;
        private readonly ShopBasket _basket;

        public BasketController(ShopBasket basket, BookStoreContext context)
        {
            _context = context;
            _basket = basket;
        }
        [HttpGet]

        [Authorize(Roles = "user")]
        public async Task<IActionResult> GetBasketView()
        {
            var items = await _basket.GetBasketItemsAsync();
            _basket.defferedBooks = items;
            ViewData["TotalSum"] = await _basket.GetTotalSumAsync();
            return View(_basket);
        }

        [Authorize(Roles = "user")]
        public  async Task<EmptyResult> AddBasketItem(int id)
        {
            await _basket.AddBasketItemAsync( _context.Book.FirstOrDefault(b => b.ID == id));

            return new EmptyResult();          
        }

       [Authorize(Roles = "user")]
        public async Task<EmptyResult> RemoveBasketItem(int id)
        {
            await _basket.RemoveBasketItemAsync(id);                    
            return new EmptyResult();                    
        }
    }
}

WebApplication6/Controllers/RolesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication6.ViewModels;
using WebApplication6.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace WebApplication6.Controllers
{
    
    [Authorize(Roles="admin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        BookStoreContext _context;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager,BookStoreContext context)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _context = context;
        }

        public async Task<IActionResult> RemoveOrderItem(int id)
        {
            var order = await _context.Order.FindAsync(id);
            if(order != null)
            {
                _context.Order.Remove(order);
                await _context.SaveChangesAsync();
            }        
            return RedirectToAction(nameof(GetAllUsersOrders));
        }
        public async Task<IActionResult> GetAllUsersOrders()
        {

            var orders = await _context.Order.AsNoTracking().ToListAsync();

            return View(orders);
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
           
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
             
                var userRoles = await _userManager.GetRolesAsync(user);
             
                var allRoles = _roleManager.Roles.ToList();
               
                var addedRoles = roles.Except(userRoles);
             
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }

        public  async Task<IActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if(user != null)
            {
                await _userManager.DeleteAsync(user);
            }
            return RedirectToAction(nameof(UserList));
        }

        public async Task<IActionResult> Details(int id)
        {

            var orderDetails = await _context.OrderDetailes.Where(od => od.OrderID == id)
                                                           .Include(od => od.Book)
                                                           .ThenInclude(b => b.Author)
                                                           .AsNoTracking()
                                                           .ToListAsync();
            return View(orderDetails);
        }
    }
}

WebApplication6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
</head>
<body>
    <header>
        <!--Navbar-->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a asp-action="Index" asp-controller="Home" class="navbar-brand  mr-2">
                <img src="~/Images/Logo.svg" />ook Store
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item ">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="AboutUs">About us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="ContactUs" asp-controller="Home">Contact us</a>
                    </li>
                </ul>

                @if (User.Identity.IsAuthenticated)
                {
                    <!--My room-->
                    <div class="dropdown">
                        <button type="button" class="bg-transparent border-0 dropdown-toggle" data-toggle="dropdown">
                            <img src="~/Images/UsersRoom.svg" />
                            <p class="d-inline text-white-50">My room</p>
                        </button>
                        <div class="dropdown-menu bg-dark">
                            <form method="post" asp-controller="Account" asp-action="Logout" class="form-inline mt-2 mt-md-0">
                                <button class="dropdown-item text-light bg-transparent ml-0" type="submit">
                                    <img src="~/Images/Logout.svg" />
                                    Logout
                                </button>
                            </form>
                            @if (User.IsInRole("admin"))
                            {
                                <div class="dropdown-divider"></div>
                                <form method="post" asp-controller="Roles" asp-action="UserList" class="form-inline mt-2 mt-md-0">
                                    <button class="dropdown-item text-light bg-transparent ml-0" type="submit">
                                        <img src="~/Images/UserList.svg" />
                                        Users
                                    </button>
                                </form>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item text-light bg-transparent" asp-action="GetAllUsersOrders" asp-controller="Roles">
                                    <img src="~/Images/OrderList.svg" />
                                    Orders
                                </a>
                            }
                            
                            @if (User.IsInRole("user"))
                            {
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item text-light bg-transparent" asp-action="GetUsersOrders" asp-controller="Account">
                                    <img src="~/Images/UsersOrderHistory.svg" />
                                    History
                                </a>
                                <div class="dropdown-divider"></div>
                                <form method="get" asp-controller="Basket" asp-action="GetBasketView" class=" mt-2 mt-md-0">
                                    <button type="submit" class=" bg-transparent dropdown-item text-light">
                                        <img src="~/Images/UsersCart.svg" />
                                        Basket
                                    </button>
                                </form>
                            }
                          </div>
                    </div>
                }

                else
                {
                    <div class="dropdown">
                        <button type="button" class="bg-transparent border-0 dropdown-toggle" data-toggle="dropdown">
                            <img src="~/Images/Account.svg" />
                            <p class="d-inline text-white-50">Account</p>
                        </button>
                        <div class="dropdown-menu bg-dark">
                            <a class="dropdown-item bg-transparent text-light" asp-controller="Account" asp-action="Login">
                                <div class="navbar-tool-icon-box">
                                    <img src="~/Images/Sign in.svg" />
                                    Sign in
                                </div>
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item bg-transparent text-light" asp-controller="Account" asp-action="Register">
                                <div class="navbar-tool-icon-box">
                                    <img src="~/Images/Sign up.svg" />
                                    Sign up
                                </div>
                            </a>
                        </div>
                    </div>

                }
            </div>
        </nav>
    </header>

    <div class="masonry-block half-width half-height no-right-margin">
        <div class="block-image" style="background-image:url(/themes/kpfu/sharing/images/block-career.jpg)"></div>
        <a href="/work/vacancies-rus">
            <table class="center-center big"><tbody><tr><td>Карьера</td></tr></tbody></table>
        </a>
    </div>

    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WebApplication6 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-ajax/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>